try:
   numero = 1200/0

except Exception as erro:
    print('Ocorreu o erro: ', erro)